# Generated by Django 3.1.7 on 2021-03-17 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import music.key
import music_importer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=5000)),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                (
                    "bpm",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Bpm must be positive"
                            )
                        ]
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            (music.key.OpenKey["D1"], "1d"),
                            (music.key.OpenKey["D2"], "2d"),
                            (music.key.OpenKey["D3"], "3d"),
                            (music.key.OpenKey["D4"], "4d"),
                            (music.key.OpenKey["D5"], "5d"),
                            (music.key.OpenKey["D6"], "6d"),
                            (music.key.OpenKey["D7"], "7d"),
                            (music.key.OpenKey["D8"], "8d"),
                            (music.key.OpenKey["D9"], "9d"),
                            (music.key.OpenKey["D10"], "10d"),
                            (music.key.OpenKey["D11"], "11d"),
                            (music.key.OpenKey["D12"], "12d"),
                            (music.key.OpenKey["M1"], "1m"),
                            (music.key.OpenKey["M2"], "2m"),
                            (music.key.OpenKey["M3"], "3m"),
                            (music.key.OpenKey["M4"], "4m"),
                            (music.key.OpenKey["M5"], "5m"),
                            (music.key.OpenKey["M6"], "6m"),
                            (music.key.OpenKey["M7"], "7m"),
                            (music.key.OpenKey["M8"], "8m"),
                            (music.key.OpenKey["M9"], "9m"),
                            (music.key.OpenKey["M10"], "10m"),
                            (music.key.OpenKey["M11"], "11m"),
                            (music.key.OpenKey["M12"], "12m"),
                        ],
                        max_length=3,
                        validators=[],
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music_importer.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music_importer.artist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music_importer.artist"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
