# Generated by Django 3.1.7 on 2021-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_importer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="musictrack",
            managers=[],
        ),
    ]
