# Generated by Django 3.1.7 on 2021-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_collection", "0001_initial"),
        ("music_importer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musictrack",
            name="collections",
            field=models.ManyToManyField(to="music_collection.MusicCollection"),
        ),
    ]
