# Generated by Django 3.1.7 on 2021-03-17 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("music_importer", "0002_auto_20210317_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="musictrack",
            name="date_released",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
