# Generated by Django 3.1.7 on 2021-03-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_importer", "0006_auto_20210322_0906"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("name", "artist")},
        ),
    ]
