# Generated by Django 3.1.7 on 2021-03-22 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music_importer", "0009_auto_20210322_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("name", "artist", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="artist",
            unique_together={("name", "user")},
        ),
    ]
