# Generated by Django 3.1.7 on 2021-03-22 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music_importer", "0010_auto_20210322_1123"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("name", "user")},
        ),
    ]
