# Generated by Django 3.1.7 on 2021-03-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_importer", "0011_auto_20210322_1500"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="album",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artist",
            unique_together=set(),
        ),
    ]
