# Generated by Django 3.1.7 on 2021-03-22 21:10

from django.db import migrations
import music_importer.models


class Migration(migrations.Migration):

    dependencies = [
        ("music_importer", "0013_auto_20210322_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musictrack",
            name="key",
            field=music_importer.models.KeyField(blank=True, null=True),
        ),
    ]
