# Generated by Django 3.1.7 on 2021-03-31 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_collection", "0001_initial"),
        ("music", "0002_musictrackwithnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musictrackwithnumber",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track",
                to="music_collection.musiccollection",
            ),
        ),
        migrations.AlterField(
            model_name="musictrackwithnumber",
            name="track_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="music.musictrack",
            ),
        ),
    ]
