# Generated by Django 3.1.7 on 2021-03-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_collection", "0001_initial"),
        ("music", "0003_auto_20210331_2000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musictrackwithnumber",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="music_collection.musiccollection",
            ),
        ),
    ]
