# Generated by Django 3.1.7 on 2021-04-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_auto_20210331_2002"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="musictrackwithnumber",
            options={"ordering": ["number"]},
        ),
    ]
