version: "3.9"
   
services:
  db:
    image: postgres:12.0-alpine
    env_file :
      - ./.env.docker.dev
    volumes:
      - postgres_data:/var/lib/postgresql/
  web:
    env_file :
      - ./.env.docker.dev
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djRDO:/djRDO
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
