version: "2"
   
services:
  db:
    image: postgres:12.0-alpine
    env_file :
      - ./.env.docker.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/
  web:
    env_file :
      - ./.env.docker.dev
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data_dev:
