version: "2"
   
services:
  db:
    image: postgres:12.0-alpine
    env_file :
      - .env.docker.prod.postgre
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
  web:
    env_file :
      - .env.docker.prod.djrdo
    build: 
      context: .
      dockerfile : Dockerfile.prod.demo
    command: hypercorn --bind 0.0.0.0:8000 djRDO.asgi:application 
    expose :
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/djRDO/web/static
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/djRDO/web/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.docker.prod.nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  postgres_data_prod:
  static_volume:
  certs:
  html:
  vhost:
