# Generated by Django 3.1.7 on 2021-03-31 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("music_collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musiccollection",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 31, 10, 21, 50, 991675, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
