# Generated by Django 3.1.7 on 2021-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_collection", "0002_musiccollection_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiccollection",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
